# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1578b4d6ec407ae13896337deea006d65b2546be01c5d6f88c3a331fb2ae25ca33019ec7851ec28fb67bc79857e5684be7d49f8ca0298e89b538d97c5d08ea2

  
  
  
test:
  secret_key_base: 77b1e89e27a1a8967dd6d26129435d917200e5486af4bcf8869942cad90a3e98fc8e91e818563965d3fe1c9347d7b3bac1a665aeaabc1212f5947d6cfb632290
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
